In [1]:
import numpy as np
one_d=np.array([1,2,3,4,5])
print("1D Array:",one_d)

1D Array: [1 2 3 4 5]


In [6]:
two_d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n",two_d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
three_d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D Array:\n",three_d)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
print("\nArray Properties")
print("Shape:",two_d.shape)
print("Size:",two_d.size)
print("Data Type:",two_d.dtype)


Array Properties
Shape: (3, 3)
Size: 9
Data Type: int32


In [15]:
#Creating special array
zeros=np.zeros((2,3))
print("Zeros Array:\n",zeros)

ones=np.ones((3,4))
print("Ones Array:\n",ones)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
identity=np.eye(3)
print("Identity Matrix:\n",identity)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#Linsapce And Arange
linspace_array=np.linspace(0,10,5)
print("Linspace Array:\n",linspace_array)

arange_array=np.arange(0,100,5)
print("Arange Array:\n",arange_array)

Linspace Array:
 [ 0.   2.5  5.   7.5 10. ]
Arange Array:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [30]:
#Array Operations
a=np.array([1,2,3])
b=np.array([4,5,6])
add=a+b
print("Sum of Arrays:\n",add)

multiply=a*b
print("Product of Arrays:\n",multiply)

scalar_multiply=b*10
print(scalar_multiply)

c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
matrix_product=np.dot(c,d)
print("Matrix Multiplication:\n",matrix_product)

Sum of Arrays:
 [5 7 9]
Product of Arrays:
 [ 4 10 18]
[40 50 60]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [33]:
#Indexing and Slicing
e=np.array([10,20,30,40,50,60])
print("Element at index 1:",e[1])
print("Elements from index 1 to 4:",e[1:5])

Element at index 1: 20
Elements from index 1 to 4: [20 30 40 50]


In [2]:
import pandas as pd
data_frame=pd.read_csv('friend_list.csv')

In [3]:
print(data_frame)

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern


In [4]:
data_frame

name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [5]:
data_frame.head()

name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager

In [6]:
data_frame.tail()

name  age        job
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [7]:
type(data_frame.job)

pandas.core.series.Series

In [9]:
data_frame.name=data_frame.name.str.upper()
data_frame.head()

name  age        job
0   JOHN   20    STUDENT
1  JENNY   30  DEVELOPER
2   NATE   30    TEACHER
3  JULIA   40    DENTIST
4  BRIAN   45    MANAGER

In [10]:
s1=pd.core.series.Series(['one','two','three'])
s2=pd.core.series.Series([1,2,3])
pd.DataFrame(data=dict(word=s1,num=s2))

word  num
0    one    1
1    two    2
2  three    3

In [4]:
df=pd.read_csv('friend_list.txt')

In [5]:
df.head()

name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager

In [6]:
df=pd.read_csv('friend_list_no_head.csv',header=None)

In [7]:
df.head()

0   1          2
0   John  20    student
1  Jenny  30  developer
2   Nate  30    teacher
3  Julia  40    dentist
4  Brian  45    manager

In [8]:
df.columns=['name','age','job']

In [9]:
df.head()

name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager